@library('jenkins-series-lib') _ 

pipeline {
    agent any 
    stages {
        stage('Use Shared Library') {
            steps {
                script{
                    buildAndTest('General-Aladdin')
                }
            }
        }
    }
}